language: go
go: 
    - 1.4
    - 1.5
    - 1.6
    - tip
install:
    - go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
    - go build -v ./...
script:
    - go test -v -cover ./...
